### ISSUE TITLE
Is this library supported?

### ISSUE THREAD

**Issue by guglielmobartelloni** [akasprzok/svadilfari#21]
I was searching for a logging library to Grafana Loki and found this. Can it be used in production?

**Comment by akasprzok** [comment]
what kind of support are you looking for?
It's free code that was written by me. I use it for my personal website and make it available for others to use.
It works well for my use case, but you might find a bug or limitation in the course of using it. In that case, you can
1. ask me for a fix, which I might have time for
2. post a fix in a PR yourself
3. fork it
4. find a different solution

https://hex.pm/packages/svadilfari the package has a little over 3k downloads on Hex.

**Comment by guglielmobartelloni** [comment]
I asked because I saw that the last commit was in 2022. So I was wondering if there is the interest in continuing to support the project. 
But you answered the question anyway thanks

**Comment by akasprzok** [comment]
Yeah I haven't needed to make any changes as it has been working without issues for me since then.
